### ISSUE TITLE
rogtemplate Build Automatically Cancelled 

### ISSUE THREAD

**Issue by stephbuon** [rOpenGov/rogtemplate#6]
Hello! I am a new contributor to rOpenGov and I am having trouble building the pkgdown page for my package, usdoj, using the rogtemplate.

I added the `.github/workfllows/rogtemplate-gh-pages.yaml` to my page (see here: https://github.com/rOpenGov/usdoj/blob/master/.github/workflows/rogtemplate-gh-pages.yaml). But the build is automatically cancelled (See: https://github.com/rOpenGov/usdoj/actions/runs/3884844046).

I am sorry if I am missing something! Thanks in advance for your help.

**Comment by pitkant** [comment]
Is this still an issue? The website seems to be live at https://ropengov.github.io/usdoj so some action was completed successfully.

Also the message "Canceling since a higher priority waiting request for 'pages build and deployment @ master' exists" implicates that maybe there was another action doing the same thing which led to automatic cancellation.

**Comment by dieghernan** [comment]
Hi @stephbuon 

That's a "non-issue". As @pitkant explained, that action is owned by GitHub, so it should be some kind of optimization rule that cancels this action if there is a newer instace of that action itself. This happens tipically when you do two commits on less than 1 minute, so the most recent run has highest priority, in your case that run was https://github.com/rOpenGov/usdoj/actions/runs/3884846008

PS: I took the liberty of changing your GH pages deployment branc to 'gh-pages' as [explained in the docs](https://ropengov.github.io/rogtemplate/#commit-to-github-and-deploy) so now the site is live with **rogtemplate**.

https://ropengov.github.io/usdoj

**Comment by stephbuon** [comment]
Thanks @dieghernan. I'm not trying to be a nuance (and I am only trying to be helpful), so if you want, I could volunteer myself to change some language in the documentation. Instead of:

"The action would create your site in the gh-pages branch" 

I could add a sentence saying that the deployment branch should be named 'gh-pages'. 

Completely up to you :)

**Comment by dieghernan** [comment]
I appreciate it, and I would be glad also if you can do that (via pull request).

Thanks

**Comment by stephbuon** [comment]
I just updated **README.md** and **README.Rmd** (via pull request). Thanks!
